class ChumbyArtOfWar {

	private static var widgetBackgroundColor:Number = 0xCCC08F;
	private static var widgetBorderColor:Number = 0x6E4911;
	private static var contentBackgroundColor:Number = 0xE6E1CF;
	private static var textColor:Number = 0x000000;

	private static var book:ArtOfWarBook = ArtOfWarBook.book;
	
	private static var timeoutInterval;
	private static var nextTimeout = 0;
	
	private static var isPlaying:Boolean = true;
	private static var isRandomPlayOrder:Boolean = true;
	
	private static var contentFormat:TextFormat;
	
	public static function main() {
		// Set stage scale mode to keep it from resizing
		//Stage.scaleMode = "noscale";
		
		// draw layout
		drawBackground();
		drawButtons();
		drawTimeout();
	
		// asset ID strings are auto-generated by FDBuild and can be inserted into
		// the currently open code file by double-clicking a resource in the tree view.

		// embedded pixel font
		var format = new TextFormat("library.Vera.ttf", 28, 0xC00000);

		_root.createTextField("title", 20, 50, 0, 270, 28);
		_root.title.autoSize = "center";
		_root.title.embedFonts = true;
		_root.title.setNewTextFormat(format);
		_root.title.text = book.title;
		
		_root.createTextField("subTitle", 21, 50, 30, 270, 14);
		_root.subTitle.autoSize = "center";
		_root.subTitle.embedFonts = true;
		format.size = 14;
		format.color = textColor;
		_root.subTitle.setNewTextFormat(format);
		_root.subTitle.text = "By " + book.author;
		
		var chapterTitle:TextField = _root.createTextField("chapterTitle", 22, 50, 60, 270, 14);
		chapterTitle.autoSize = "center";
		chapterTitle.embedFonts = true;
		format.color = widgetBorderColor;
		format.bold = true;
		chapterTitle.setNewTextFormat(format);
		
		var contentField:TextField = _root.createTextField("contentField", 23, 60, 90, 250, 140);
		//contentField.background = true;
		//contentField.backgroundColor = contentBackgroundColor;
		contentField.multiline = true;
		contentField.wordWrap = true;
		contentField.embedFonts = true;
		/*format.size = 12;
		format.color = 0x000000;
		format.bold = false;*/
		format = new TextFormat("library.DejaVuSansMono.ttf", 12);
		contentField.setNewTextFormat(format);
		contentFormat = format;
		
		nextContent();
		//setInterval(updateContent, 15000);
		//timeoutInterval = setInterval(tickTimeout, 12000);	// TODO: learn how to use setTimeout instead of hacking setInterval
		//setTimeout(tickTimeout, 12000);
		//_global['setTimeout']('ChumbyArtOfWar', 'tickTimeout', 12000);
	}
	
	private static function tickTimeout():Void {
		// Change content every 15 seconds, show timeout markers for last 3 seconds
		clearInterval(timeoutInterval);
		if (nextTimeout < 3) {
			timeoutInterval = setInterval(tickTimeout, 1000);
			_root["timeout" + nextTimeout]._visible = true;
			nextTimeout++;
		}
		else
			nextContent();
	}
	
	private static function resetTimeout():Void {
		clearInterval(timeoutInterval);
		if (isPlaying)
			timeoutInterval = setInterval(tickTimeout, 12000);
		nextTimeout = 0;
		_root.timeout0._visible = false;
		_root.timeout1._visible = false;
		_root.timeout2._visible = false;
	}
	
	private static function drawBackground():Void {
		var background:MovieClip = _root.attachMovie("library.Texture.png", "background", 0);
		_root.background._x = 0;
        _root.background._y = 0;

		/*_root.createEmptyMovieClip("background", 1);
        _root.background.beginFill(widgetBackgroundColor, 100);
        _root.background.moveTo(0, 0);
        _root.background.lineTo(270, 0);
        _root.background.lineTo(270, 240);
        _root.background.lineTo(0, 240);
        _root.background.endFill();
        _root.background._x = 50;
        _root.background._y = 0;
		
		_root.createEmptyMovieClip("border", 2);
        //_root.border.lineStyle(2, 0x000000, 100);
        _root.border.beginFill(widgetBorderColor, 100);
        _root.border.moveTo(0, 0);
        _root.border.lineTo(50, 0);
        _root.border.lineTo(50, 240);
        _root.border.lineTo(0, 240);
        _root.border.endFill();
        _root.border._x = 0;
        _root.border._y = 0;*/
		
		_root.createEmptyMovieClip("border", 1);
        _root.border.beginFill(contentBackgroundColor, 80);
        _root.border.moveTo(0, 0);
        _root.border.lineTo(250, 0);
        _root.border.lineTo(250, 170);
        _root.border.lineTo(0, 170);
        _root.border.endFill();
        _root.border._x = 60;
        _root.border._y = 60;
	}
	
	private static function drawTimeout():Void {
		for (var i:Number = 0; i < 3; i++) {
			var el = _root.createEmptyMovieClip("timeout" + i, 3 + i);
			el.beginFill(widgetBorderColor, 100);
			el.moveTo(0, 0);
			el.lineTo(6, 0);
			el.lineTo(6, 6);
			el.lineTo(0, 6);
			el.endFill();
			el._x = 288 + i * 8;
			el._y = 232;
			el._visible = false;
			//trace(el._x + " " + el._y);
		}
		//trace(_root.timeout0._x + " " + _root.timeout0._y);
	}
	
	private static function drawButtons():Void {	//TODO: Add buttons
		// Random
		// In-order
		
		// Previous
		var btn:MovieClip = createButton("btnPrevious", 10);
		btn.beginFill(widgetBorderColor, 100);
        btn.moveTo(25, 10);
        btn.lineTo(15, 10);
        btn.lineTo(15, 5);
		btn.lineTo(5, 15);
		btn.lineTo(15, 25);
		btn.lineTo(15, 20);
        btn.lineTo(25, 20);
        btn.endFill();
		btn.onPress = function():Void { ChumbyArtOfWar.previousContent(); }
        btn._x = 10;
        btn._y = 70;
		btn._visible = false;
		
		// Next
		btn = createButton("btnNext", 11);
		btn.beginFill(widgetBorderColor, 100);
        btn.moveTo(5, 10);
        btn.lineTo(15, 10);
        btn.lineTo(15, 5);
		btn.lineTo(25, 15);
		btn.lineTo(15, 25);
		btn.lineTo(15, 20);
        btn.lineTo(5, 20);
        btn.endFill();
		btn.onPress = function():Void { ChumbyArtOfWar.nextContent(); }
        btn._x = 10;
        btn._y = 110;
		
		// Play
		btn = createButton("btnPlay", 8);
		btn.beginFill(widgetBorderColor, 100);
        btn.moveTo(5, 5);
        btn.lineTo(25, 15);
        btn.lineTo(5, 25);
        btn.endFill();
		btn.onPress = function():Void { ChumbyArtOfWar.play(true); }
        btn._x = 10;
        btn._y = 150;
		btn._visible = false;
		
		// Pause
		btn = createButton("btnPause", 9);
		btn.beginFill(widgetBorderColor, 100);
        btn.moveTo(5, 5);
        btn.lineTo(12, 5);
        btn.lineTo(12, 25);
		btn.lineTo(5, 25);
        btn.endFill();
		btn.beginFill(widgetBorderColor, 100);
        btn.moveTo(25, 5);
        btn.lineTo(18, 5);
        btn.lineTo(18, 25);
		btn.lineTo(25, 25);
        btn.endFill();
		btn.onPress = function():Void { ChumbyArtOfWar.play(false); }
        btn._x = 10;
        btn._y = 150;
		
		// In Order
		btn = createButton("btnInOrder", 12);
		btn.lineStyle(2, widgetBorderColor, 100);
		btn.beginFill(widgetBorderColor, 0);
        btn.moveTo(6, 6);
		btn.lineTo(19, 6);
		btn.lineTo(24, 11);
        btn.lineTo(24, 24);
        btn.lineTo(6, 24);
        btn.endFill();
		btn.beginFill(widgetBorderColor, 100);
        btn.moveTo(11, 11);
        btn.lineTo(19, 15);
		btn.lineTo(11, 19);
        btn.endFill();
		btn.onPress = function():Void { ChumbyArtOfWar.setRandomPlayOrder(false); }
        btn._x = 10;
        btn._y = 190;
		
		// Radom
		btn = createButton("btnRandom", 13);
		btn.lineStyle(2, widgetBorderColor, 100);
		btn.beginFill(widgetBorderColor, 0);
        btn.moveTo(6, 6);
		btn.lineTo(19, 6);
		btn.lineTo(24, 11);
        btn.lineTo(24, 24);
        btn.lineTo(6, 24);
        btn.endFill();
		var format = new TextFormat("library.Vera.ttf", 14, widgetBorderColor);
		btn.createTextField("qmark", 14, 6, 6, 18, 18);
		btn.qmark.autoSize = "center";
		btn.qmark.embedFonts = true;
		btn.qmark.setNewTextFormat(format);
		btn.qmark.text = "?";
		btn.onPress = function():Void { ChumbyArtOfWar.setRandomPlayOrder(true); }
		btn._x = 10;
        btn._y = 190;
		btn._visible = false;
	}
	
	private static function createButton(name:String, depth:Number):MovieClip {
		var btn:MovieClip = _root.createEmptyMovieClip(name, depth);
        
		btn.beginFill(widgetBackgroundColor, 80);
        btn.moveTo(0, 0);
        btn.lineTo(30, 0);
        btn.lineTo(30, 30);
        btn.lineTo(0, 30);
        btn.endFill();
		
		return btn;
	}
	
	private static function changeContentFontSize(textLength:Number) {
		if (textLength < 190)
			contentFormat.size = 12;
		else if (textLength < 345)
			contentFormat.size = 11;
		else if (textLength < 430)
			contentFormat.size = 10;
		else
			contentFormat.size = 9;
		_root.contentField.setNewTextFormat(contentFormat);
	}
	
	private static function previousContent():Void {
		resetTimeout();
		
		var content:Object = book.previousContent();
		
		changeContentFontSize(content.text.length);
		_root.chapterTitle.text = content.title;
		_root.contentField.text = content.text;
	}
	
	private static function nextContent():Void {
		resetTimeout();
		
		var oldChapter:String = _root.chapterTitle.text;
		var oldContent:String = _root.chapterField.text;
		
		do {
			var content:Object = isRandomPlayOrder ? book.randomContent() : book.nextContent();
			
			changeContentFontSize(content.text.length);
			_root.chapterTitle.text = content.title;
			_root.contentField.text = content.text;
		} 
		while (oldChapter == _root.chapterTitle.text && // Check if content has not changed
		       oldContent == _root.contentField.text);  // (can happen during random play).
	}
	
	private static function play(toPlay:Boolean):Void {
		isPlaying = toPlay;
		if (toPlay)
			nextContent();
		else
			resetTimeout();
		
		_root.btnPlay._visible = !isPlaying;
		_root.btnPause._visible = isPlaying;
	}
	
	private static function setRandomPlayOrder(isRandom:Boolean):Void {
		isRandomPlayOrder = isRandom;
		
		_root.btnInOrder._visible = isRandomPlayOrder;
		_root.btnRandom._visible = !isRandomPlayOrder;
		_root.btnPrevious._visible = !isRandomPlayOrder;
	}
}